### ISSUE TITLE
Include Azure setup for multi-tenant registrations?

### ISSUE THREAD

**Issue by iambmelt** [microsoftgraph/nodejs-connect-rest-sample#21]
Per convo with @jasonjoh we should consider suggesting making the app multi-tenant during registration in case a developer tries testing with an account other than the one used to register the app.

**Comment by geoah** [comment]
Is there any progress or links relating to this? The process would be very useful.

**Comment by iambmelt** [comment]
Hi @geoah - for a detailed set of documentation on this see [this](https://msdn.microsoft.com/en-us/library/hh534478.aspx) article on MSDN.

For the super-quick 'how do I make a registration multi-tenant?':

1. Log in to manage.windowsazure.com (Ignore the prompts the use the new management portal, these instructions are for the older portal).
2. On the left rail, scroll down to 'Active Directory', select it
3. In the middle pane, you'll see your instances of Active Directory - select the tenant in which the targeted application is registered.
4. After selecting your tenant, select the 'Applications' tab (top-center) to see a list of registered apps. Select the application which you would like to make multi-tenant from this list.
5. After selecting the application, select the 'Configure' tab (top-center).
6. Within the Configure tab, scroll down to 'Application is Multi-Tenant?' and switch the toggle control to 'YES'

Does this help?

**Comment by Ricalo** [comment]
Hi, with #41 the sample supports the App Model v2 along with users from multiple tenants. Feel free to reopen this issue if this does not support your multi-tenant scenario.
