### ISSUE TITLE
"The user or administrator has not consented to use the application"

### ISSUE THREAD

**Issue by prc322** [microsoftgraph/nodejs-connect-rest-sample#50]
I've created an app at https://apps.dev.microsoft.com and configured the example as mentioned at https://graph.microsoft.io/en-us/docs/get-started/nodejs

After clicking the login button the example redirects me to the Microsoft login page where I enter my credentials and accept that the app will be able to User.Read. After successfully logging in Microsoft redirects me back to the example, with an auth code in the query parameter "code" - as it should be.

However, this is where the example code crashes. Console output (unnecessary info redacted):

```bash
GET / 302 0.709 ms - 54
GET /login 304 2.611 ms - -
GET /stylesheets/style.css 304 0.727 ms - -
AADSTS65001: The user or administrator has not consented to use the application with ID 'APPLICATIONID'. Send an interactive authorization request for this user and resource.
Trace ID: 4a246de5-9dc9-4a96-9458-a17c894776cd
Correlation ID: a8e10a23-9aa7-40b3-89ad-4f2272742356
Timestamp: 2016-12-06 12:03:38Z
GET /login?code=CODE&session_state=SESSIONSTATE 500 380.747 ms -
```

I consented to use the app at the Microsoft login page. What am I missing?

**Comment by DianeD** [comment]
Hi @prc322 . Thanks for reporting this issue. I downloaded the project and followed the steps in the walkthrough but haven't been able to reproduce it (tried with different users/tenants/browsers). I've occasionally encountered this error when testing various apps, sometimes for reasons not apparent to me. I think re-registering the app has fixed it before, but I'm going to try to find some other workaround ideas.

You mention that you're prompted for User.Read, but you should be seeing three permissions: Access your data anytime, Sign you in and read your profile, and Send mail as you (or similar for MSA users). Just want to confirm this is also what you see.

**Comment by DianeD** [comment]
Hi @prc322 . I haven't found much actionable info about this issue that might apply to this sample. Is it still reproducing? Did you try creating a new app registration? 

Some things that might help troubleshoot, based on related issues:
You can capture the access token, paste it in [http://jwt.io](http://jwt.io), and check that the "scp" parameter grants 'Mail.Send User.Read' access. (Note that in the Consent dialog, you'd also be prompled for the offline_access perm.) To capture the token, you can use Fiddler or put a breakpoint in authHelper.js in the oauth2.getOAuthAccessToken callback (line 66).

Check if there are issues using the 'common' authority. In authHelper.js, replace 'common' in the authority URL with your tenant ID. The tenant ID is the "tid" parameter in the jwt, or you can get it from https://portal.azure.com in the AAD's Properties pane. Are you using a test tenant or an actual tenant?

**Comment by DianeD** [comment]
@prc322 Thanks again for reporting. Please reopen if you're still getting this error.
