### ISSUE TITLE
Poor handling of undefined profile fields

### ISSUE THREAD

**Issue by BurtHarris** [microsoftgraph/nodejs-connect-rest-sample#57]
Running this sample, after resolving the login problem, I get the following exception, which seems to be caused by undefined fields in `req.user.profile`

```
TypeError: Cannot read property '0' of undefined
    at renderSendMail (c:\try\AppIDEx\nodejs-connect-rest-sample\nodejs-connect-rest-sample-master\routes\index.js:60:43)
    at router.get (c:\try\AppIDEx\nodejs-connect-rest-sample\nodejs-connect-rest-sample-master\routes\index.js:29:5)
    at Layer.handle [as handle_request] (c:\try\AppIDEx\nodejs-connect-rest-sample\nodejs-connect-rest-sample-master\node_modules\express\lib\router\layer.js:95:5)
    at next (c:\try\AppIDEx\nodejs-connect-rest-sample\nodejs-connect-rest-sample-master\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (c:\try\AppIDEx\nodejs-connect-rest-sample\nodejs-connect-rest-sample-master\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (c:\try\AppIDEx\nodejs-connect-rest-sample\nodejs-connect-rest-sample-master\node_modules\express\lib\router\layer.js:95:5)
    at c:\try\AppIDEx\nodejs-connect-rest-sample\nodejs-connect-rest-sample-master\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (c:\try\AppIDEx\nodejs-connect-rest-sample\nodejs-connect-rest-sample-master\node_modules\express\lib\router\index.js:335:12)
    at next (c:\try\AppIDEx\nodejs-connect-rest-sample\nodejs-connect-rest-sample-master\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (c:\try\AppIDEx\nodejs-connect-rest-sample\nodejs-connect-rest-sample-master\node_modules\express\lib\router\index.js:174:3)
```

**Comment by jamescro** [comment]
Thanks for catching this bug. We will investigate and fix ASAP.

**Comment by faultylee** [comment]
Hi, I'm getting the same error, and I have a peek inside req.user.profile
```
     sub: '*****************************************',
     oid: undefined,
     upn: undefined,
     displayName: undefined,
     name: [Object],
     emails: undefined,
```

**Comment by jamescro** [comment]
Thanks for the update. Just for clarity, do you see this problem when you run the quick start, or are you seeing it after downloading or cloning the repo and registering and configuring the client yourself. The problem reported in the first note in this thread is a downstream result of a problem with the quick start, which registers an incorrect redirect URI for the client. Once that problem is fixed (and a fix is on the way), then the problem originally reported in this issue will go away.

**Comment by faultylee** [comment]
@jamescro I didn't use the quickstart nor cloning the repo, to save time, I copy-and-paste the content of the needed files into https://glitch.com/edit/#!/cute-fur I managed to get most part working except this. From the error it doesn't seems to be issue running this in `glitch.com`

**Comment by jamescro** [comment]
Thanks. After we fix the quick start issue, I'll look into creating better handling of null and undefined values.

**Comment by faultylee** [comment]
```
    display_name: req.user.profile.displayName,
    email_address: req.user.profile.emails[0].address
```
The code at [route/index.js#L59](https://github.com/microsoftgraph/nodejs-connect-rest-sample/blob/master/routes/index.js#L59) needs both `displayName` & `email[0].address`. Even without null handling, why would the profile be `null` to begin with?

**Comment by jamescro** [comment]
I don't know anything about the account you're using, but it appears that this one user has nothing configured for the displayName property. This user also appears to have no email addresses. I do see something for the name property, though, so the user appears to exist. Is this a test account?

**Comment by faultylee** [comment]
Although it's showing 'name: [Object]', but when I go into `name`, it's `undefined` as well.

I'm using my work account. Our company have recently migrated to Office 365 (including AD), so I was taking this opportunity to explore pushing data into Excel Online, like I used to do in Google Spreadsheet. The Graph API seems to be the way to go, and I stumble into this sample. I used this as a quick test to see how much work is needed to get it up and working.

**Comment by jamescro** [comment]
If your organization has recently moved to O365, then perhaps some of the data hasn't fully migrated. You might want to talk with an admin about this.
If you're interested in Excel operations with Graph, you can see a number of Excel operations in this sample:

https://github.com/microsoftgraph/uwp-csharp-snippets-sample

**Comment by jamescro** [comment]
As I mentioned earlier, the first reported instance of this problem in this issue was really a downstream result of a more sever problem: an incorrect redirect URI was being registered for the client. That problem has been resolved. 

I'll create a work item for better handling empty user profile properties.

**Comment by jamescro** [comment]
Checked in a fix for this. Closing.
