### ISSUE TITLE
Questionable URL in CONTRIBUTING.MD

### ISSUE THREAD

**Issue by BurtHarris** [microsoftgraph/nodejs-connect-rest-sample#58]
The CONTRIBUTING.MD instructions include instructions to issue the following command:
```
git remote add upstream https://github.com/OfficeDev/microsoft-graph-docs.git
```
The *OfficeDev* URL above seems questionable for this project.   Is stale information from another project?

**Comment by jamescro** [comment]
Thanks for catching this. That section doesn't even apply to code sample contributions, so I removed it.
