### ISSUE TITLE
Questionable URL in CONTRIBUTING.MD

### ISSUE THREAD

**Issue by BurtHarris** [microsoftgraph/nodejs-connect-rest-sample#59]
The CONTRIBUTING.MD instructions include instructions to issue the following command:
```
git remote add upstream https://github.com/OfficeDev/microsoft-graph-docs.git
```
The *OfficeDev* URL above seems questionable for this porject?   Is stale information from another project?

**Comment by jamescro** [comment]
See  issue 58: https://github.com/microsoftgraph/nodejs-connect-rest-sample/issues/58
