### ISSUE TITLE
Question: MSAL vs Passport

### ISSUE THREAD

**Issue by BurtHarris** [microsoftgraph/nodejs-connect-rest-sample#61]
I see this sample uses the NPM modules [passport](https://www.npmjs.com/package/passport) & [passport-azure-ad](https://www.npmjs.com/package/passport-azure-ad) rather than [msal](https://www.npmjs.com/package/msal), while msal seems to be played up in the recent Build conference.

Is there some underlying reason for this?   Does msal support the same scenario?

**Comment by jamescro** [comment]
We are working to update our samples to use MSAL and haven't gotten to all of them yet. The existing MSAL.js supports only client-side applications, so it won't work with this sample. We will eventually use MSAL whenever a library is available.
