### ISSUE TITLE
QuickStart README.md references non-existent files.

### ISSUE THREAD

**Issue by simra** [microsoftgraph/nodejs-connect-rest-sample#62]
The README in the zip archive provided by quickstart has incorrect instructions, referencing some non-existent .js configuration files.  The repo README is correct and it looks like the quickstart archive just needs updating.

**Comment by jamescro** [comment]
Thanks for the update. This will be remedied as soon as we can deploy a new version of the quick start.

**Comment by jamescro** [comment]
This should be fixed now.
