### ISSUE TITLE
Quickstart fails w/ TypeError: Cannot read property 'render' of undefined

### ISSUE THREAD

**Issue by BurtHarris** [microsoftgraph/nodejs-connect-rest-sample#63]
**Environment**
    node v6.10.3
    npm 3.10.10

**Repro**

1. From https://developer.microsoft.com/en-us/graph/graph/quick-start create a new NodeJS project. With copy/paste of application secret.

2.  Download/unzip the generated sample application.  At a command prompt in resulting directory:

        npm I
        npm start
        
3. Start web browser at http://localhost:3000

**Results**

connect and login work as expected, but when I press the "send mail" button, the node app crashes

C:\try\nodejs-connect-rest-sample-master\routes\index.js:139
  res.render('error', {
     ^

    TypeError: Cannot read property 'render' of undefined
    at renderError (C:\try\nodejs-connect-rest-sample-master\routes\index.js:139:6)
    at graphHelper.getProfilePhoto (C:\try\nodejs-connect-rest-sample-master\routes\index.js:73:19)
    at request.get.set.end (C:\try\nodejs-connect-rest-sample-master\utils\graphHelper.js:35:6)
    at Request.callback (C:\try\nodejs-connect-rest-sample-master\node_modules\superagent\lib\node\index.js:688:3)
    at C:\try\nodejs-connect-rest-sample-master\node_modules\superagent\lib\node\index.js:883:18
    at IncomingMessage.<anonymous> (C:\try\nodejs-connect-rest-sample-master\node_modules\superagent\lib\node\parsers\json.js:16:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)

**Comment by BurtHarris** [comment]
P.S.  I ran through this from scratch, just as described above.   Still get the error.   I've confirmed the client ID and clientSecret in config.js match the developer.microsoft.com portal.   This looks unrelated to login to me.

**Comment by jamescro** [comment]
I took a closer look at the error message, and now I know what this is. I'm assuming that your account doesn't have a profile photo. When I sign in with an account that has no profile photo, I get the error you're seeing. When I sign in with an account that does have a profile photo, I see no problem.
The sample therefore needs to handle that use case.

**Comment by BurtHarris** [comment]
So another example of #57...

**Comment by BurtHarris** [comment]
Perhaps the sample should be written in TypeScript with the strict null checking enabled.

**Comment by jamescro** [comment]
This problem is similar to #57, but that one is also more of a downstream effect of the sample not being configured correctly. In that case, the sample won't work, but better error handling would be nice in that scenario. This is a problem that will happen because even when the "get profile photo" operation works on commercial accounts, some accounts will still not have profile photos, so the code should definitely account for that.

And yes, we'd like to rewrite this and other JS sample in TypeScript, but we're not currently resourced for it. We are always open to pull requests, though. :-)

**Comment by jamescro** [comment]
We've pushed a number of changes to this repo. Could you try again with the latest version?

**Comment by BurtHarris** [comment]
@jamescro I'm a bit busy right now.

**Comment by jamescro** [comment]
Just checked in a fix for this. Closing
