### ISSUE TITLE
Unable to connect to microsoft graph

### ISSUE THREAD

**Issue by PranavSwaroop** [microsoftgraph/nodejs-connect-rest-sample#71]
Hi,
After clicking "Connect to Microsoft Graph" still the page does not load anything. It stops in the main page itself.

Any suggestions how to resolve this issue.

**Comment by jamescro** [comment]
Which browser are you using? Could you check your security settings and make sure that you're not blocking popups?

**Comment by jamescro** [comment]
Could you go to this page:
https://developer.microsoft.com/en-us/graph/quick-start
And choose the Node quick start from there. That will give you a preconfigured version of this same sample. If the sample works when you configure it as a quick start, then you can compare the app registrations to see what might be causing the problem.

**Comment by jamescro** [comment]
Closing for now. Please reopen if you see the same problem in the quick start version of this sample.
