### ISSUE TITLE
Invalid value for redirectUrl

### ISSUE THREAD

**Issue by brucelane** [microsoftgraph/nodejs-connect-rest-sample#72]
hello,
I follow all the steps to setup this repo, but I get this error:
`TypeError: Invalid value for redirectUrl.The URL must be valid and be https://`

My `config.js` contains `redirectUrl: 'https://localhost:3000/'`

Any hint?
Thank you

**Comment by jamescro** [comment]
This looks like a configuration issue. Could you go to this page:
https://developer.microsoft.com/en-us/graph/quick-start
And choose the Node quick start from there. That will give you a preconfigured version of this same sample. If the sample works when you configure it as a quick start, then you can compare the app registrations to see what might be causing the problem.

**Comment by brucelane** [comment]
yes, it works with this quick start, thank you!
I was using https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-devquickstarts-node-web

**Comment by jamescro** [comment]
Thanks. It looks like there might be an issue with that topic, since others who are using it seem to be having the same problem. Could you post a question about that topic to StackOverflow?

https://stackoverflow.com/questions/tagged/azure-active-directory

**Comment by brucelane** [comment]
done here: https://stackoverflow.com/questions/47516669/invalid-value-for-redirecturl-following-active-directory-v2-devquickstarts-node

**Comment by jamescro** [comment]
Thanks. Since the code in the Node quick start is identical to the code in this repo, the issue you capture in the SO question must be the real problem. Closing this issue for now. Please reopen or file another issue if you have any other problems with this sample.
