### ISSUE TITLE
Is that the guideline have some ERROR?

### ISSUE THREAD

**Issue by wudeyong** [microsoftgraph/nodejs-connect-rest-sample#74]
Hi:

   I found that guideline in README **#Register the application** 8._Enter http://localhost:3000/login
 as the Redirect URI._ have an error.Maybe the Redirect URI should be http://localhost:3000/token.

thanks.

DavinWu

**Comment by jamescro** [comment]
Thanks for alerting us to this issue. I've updated the redirect URI in the readme.
