### ISSUE TITLE
sample doesn't render the "emailSender" view

### ISSUE THREAD

**Issue by mconstantin** [microsoftgraph/nodejs-connect-rest-sample#76]
Trying to use this sample.. it prompts for signing in and consent, but afterwards it lands back on the home page (w/ the Connect to Microsoft Graph button).
I see the request to the /token?code=...&state=... endpoint, but it redirects to the passport failure endpoint, which is '/'.
How can I get some additional info on why the authentication failed?

**Comment by craig-pulliam** [comment]
Similar issue with me except when I try to tinker with this project at all it puts me in a sign in loop. If I run the sterile sample it works perfectly fine. Obviously its something I'm doing and not the project itself but even when I undo any changes I made it will continue to loop me.

**Comment by jasonjoh** [comment]
@mconstantin we're archiving this sample as it's no longer being maintained. We're replacing it with the following: https://github.com/microsoftgraph/msgraph-training-nodeexpressapp.
