### ISSUE TITLE
getting invalid request errors & reply url errors while deploying as azure site

### ISSUE THREAD

**Issue by luckyhegde** [microsoftgraph/nodejs-connect-rest-sample#77]
Ive Deployed the Node js web app as .azurewebsites.net , while connecting to the graph getting errors like invalid request with & unable to validate token also error AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application even though the right redirect is configured. Please help or suggest how to deploy the nodejs app to azure site

**Comment by jasonjoh** [comment]
@luckyhegde we're archiving this sample as it's no longer being maintained. We're replacing it with the following: https://github.com/microsoftgraph/msgraph-training-nodeexpressapp.
