### ISSUE TITLE
error handling issue

### ISSUE THREAD

**Issue by edwardkoval** [microsoftgraph/nodejs-connect-rest-sample#78]
https://github.com/microsoftgraph/nodejs-connect-rest-sample/blob/a3d89c2280d4776c3a45a8541b8636b19d6d75b4/app.js#L99

Looks like line 99 will always override the error handling on line 87

**Comment by jasonjoh** [comment]
@edwardkoval we're archiving this sample as it's no longer being maintained. We're replacing it with the following: https://github.com/microsoftgraph/msgraph-training-nodeexpressapp.
