### ISSUE TITLE
Where are you getting the access token from?

### ISSUE THREAD

**Issue by DaveVoyles** [microsoftgraph/nodejs-connect-rest-sample#80]
In [`nodeSample.js`](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/samples/node/node-sample.js) it looks like the token is coming from the [`secrets.example.json`.](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/samples/node/secrets.example.json)

I don't understand how to store it in there. I thought we receive the token when authenticate with azure AAD, so how is the token stored in this secrets file?

**Comment by jasonjoh** [comment]
@DaveVoyles we're archiving this sample as it's no longer being maintained. We're replacing it with the following: https://github.com/microsoftgraph/msgraph-training-nodeexpressapp.
